// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LUser _$LUserFromJson(Map<String, dynamic> json) {
  return LUser(
    id: json['_id'] as String,
    uid: json['uid'] as String?,
    fullName: json['fullName'] as String?,
    phone: json['phone'] as String?,
    email: json['email'] as String?,
    address: json['address'] as String?,
    avatar: json['avatar'] as String?,
    position: json['position'] as String?,
    plant: json['plant'] as String?,
    area: (json['area'] as num?)?.toDouble(),
    locationLat: (json['locationLat'] as num?)?.toDouble(),
    locationLng: (json['locationLng'] as num?)?.toDouble(),
    type: json['type'] as String?,
    status: json['status'] as String?,
    password: json['password'] as String?,
    updatedAt: json['updatedAt'] as String?,
    createdAt: json['createdAt'] as String?,
    point: json['point'] as int?,
    totalPoint: json['totalPoint'] as int?,
    province: json['province'] as String?,
    provinceId: json['provinceId'] as String?,
    district: json['district'] as String?,
    districtId: json['districtId'] as String?,
    cardNumber: json['cardNumber'] as String?,
    ward: json['ward'] as String?,
    wardId: json['wardId'] as String?,
  );
}

Map<String, dynamic> _$LUserToJson(LUser instance) => <String, dynamic>{
      '_id': instance.id,
      'uid': instance.uid,
      'fullName': instance.fullName,
      'phone': instance.phone,
      'email': instance.email,
      'address': instance.address,
      'avatar': instance.avatar,
      'position': instance.position,
      'plant': instance.plant,
      'area': instance.area,
      'locationLat': instance.locationLat,
      'locationLng': instance.locationLng,
      'type': instance.type,
      'status': instance.status,
      'password': instance.password,
      'updatedAt': instance.updatedAt,
      'createdAt': instance.createdAt,
      'point': instance.point,
      'totalPoint': instance.totalPoint,
      'province': instance.province,
      'district': instance.district,
      'ward': instance.ward,
      'provinceId': instance.provinceId,
      'districtId': instance.districtId,
      'wardId': instance.wardId,
      'cardNumber': instance.cardNumber,
    };

UserModel _$UserModelFromJson(Map<String, dynamic> json) {
  return UserModel(
    json['id'] as String,
    json['sex'] as String,
    json['username'] as String,
    json['fullname'] as String,
    json['local'] as String,
    json['avatar'] as String,
    json['phone'] as String,
    json['loginType'] as String,
    json['cityCode'] as String,
    json['nationalId'] as String,
    json['dateOfBirth'] as String,
    json['email'] as String,
    json['experience'] as String,
    json['workingHour'] as String,
    json['expectedSalary'] as String,
    json['nationalIdFrontImage'] as String,
    json['nationalIdBackImage'] as String,
    json['identityVideo'] as String,
    json['accountType'] as String,
    (json['rate'] as num).toDouble(),
    json['isVerified'] as bool,
    json['isNewUser'] as bool,
    json['money'] as String,
    json['nameCompany'] as String,
    json['avatarCompany'] as String,
    json['contactNameCompany'] as String,
    json['contactPhoneCompany'] as String,
    json['contactEmailCompany'] as String,
    json['allowNotification'] as bool,
  );
}

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'id': instance.id,
      'sex': instance.sex,
      'username': instance.username,
      'fullname': instance.fullname,
      'local': instance.local,
      'avatar': instance.avatar,
      'phone': instance.phone,
      'loginType': instance.loginType,
      'cityCode': instance.cityCode,
      'nationalId': instance.nationalId,
      'dateOfBirth': instance.dateOfBirth,
      'email': instance.email,
      'experience': instance.experience,
      'workingHour': instance.workingHour,
      'expectedSalary': instance.expectedSalary,
      'nationalIdFrontImage': instance.nationalIdFrontImage,
      'nationalIdBackImage': instance.nationalIdBackImage,
      'identityVideo': instance.identityVideo,
      'accountType': instance.accountType,
      'rate': instance.rate,
      'isVerified': instance.isVerified,
      'isNewUser': instance.isNewUser,
      'money': instance.money,
      'nameCompany': instance.nameCompany,
      'avatarCompany': instance.avatarCompany,
      'contactNameCompany': instance.contactNameCompany,
      'contactPhoneCompany': instance.contactPhoneCompany,
      'contactEmailCompany': instance.contactEmailCompany,
      'allowNotification': instance.allowNotification,
    };
